name: ex4
version: 0.0.1
author: Thomas Chabot <thomas.chabot.1@gmail.com>
description: exercice 4 utilisant la library de dartlero
homepage: http://ondart.me/
dependencies:
  dartlero:
    git: git://github.com/dzenanr/dartlero.git